#!/usr/bin/env python3
"""
Create a GitHub-friendly report for pending OceanCloud comments.

The script reads pending comments from the Cloudflare Worker admin API and writes
data/comment-moderation/pending-comments.md. It intentionally omits comment body
text by default so a pull request does not expose unmoderated user content.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Repo root path for file output and relative path calculations.
ROOT = Path(__file__).parent.parent
# Markdown report destination consumed by GitHub Actions/PR flow.
REPORT = ROOT / "data" / "comment-moderation" / "pending-comments.md"
# Base URL for the comment admin API endpoint.
API_BASE = os.environ.get("COMMENTS_API_BASE", "https://oceancloud-ai-proxy.oceancloud-ai-proxy.workers.dev").rstrip("/")
# Required bearer token used to authenticate admin API calls.
ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "").strip()
# Optional toggle to include short comment body previews in reports.
INCLUDE_BODY_PREVIEW = os.environ.get("INCLUDE_COMMENT_BODY_PREVIEW", "").strip().lower() in {"1", "true", "yes"}


def fetch_pending() -> list[dict]:
    if not ADMIN_TOKEN:
        print("[error] ADMIN_TOKEN environment variable is required", file=sys.stderr)
        sys.exit(2)

    # Curl command definition for the pending-comments API query.
    cmd = [
        "curl",
        "-sf",
        "--max-time",
        "30",
        "-H",
        f"Authorization: Bearer {ADMIN_TOKEN}",
        "-H",
        "Origin: https://oceancloudconsults.com",
        "-H",
        "Accept: application/json",
        "-H",
        "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        f"{API_BASE}/comments/admin?status=pending",
    ]

    # Raw process result containing stdout JSON payload and stderr diagnostics.
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"[error] curl failed (exit {result.returncode}): {result.stderr}", file=sys.stderr)
        sys.exit(1)

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        print(f"[error] invalid JSON from API: {exc}\nBody: {result.stdout[:200]}", file=sys.stderr)
        sys.exit(1)

    # API payload field containing pending comment objects.
    comments = payload.get("comments", [])
    return comments if isinstance(comments, list) else []


def escape_table(value: object) -> str:
    text = str(value or "")
    return text.replace("|", "\\|").replace("\n", " ").strip()


def body_preview(comment: dict) -> str:
    body = str(comment.get("body", "")).strip().replace("\n", " ")
    if len(body) > 160:
        body = body[:157].rstrip() + "..."
    return escape_table(body)


def render_report(comments: list[dict]) -> str:
    # UTC timestamp displayed at the top of the moderation report.
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Pending Comment Moderation",
        "",
        f"Generated: {now}",
        f"Pending comments: {len(comments)}",
        "",
        "Moderate comments here: https://oceancloudconsults.com/comments-admin.html",
        "",
        "> This report is generated by GitHub Actions from the Cloudflare Worker comments API. Approval still happens in the moderation page.",
        "",
    ]

    if not comments:
        lines.append("No pending comments at the time of this check.")
        lines.append("")
        return "\n".join(lines)

    headers = ["ID", "Page", "Reply To", "Author", "Created"]
    if INCLUDE_BODY_PREVIEW:
        headers.append("Body Preview")
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join("---" for _ in headers) + "|")

    for comment in comments:
        row = [
            escape_table(comment.get("id")),
            escape_table(comment.get("slug")),
            escape_table(comment.get("parent_id") or ""),
            escape_table(comment.get("display_name")),
            escape_table(comment.get("created_at")),
        ]
        if INCLUDE_BODY_PREVIEW:
            row.append(body_preview(comment))
        lines.append("| " + " | ".join(row) + " |")

    lines.extend([
        "",
        "## Review Steps",
        "",
        "1. Open the moderation page.",
        "2. Enter the Worker `ADMIN_TOKEN`.",
        "3. Approve or reject each pending comment.",
        "4. Close or merge this PR after review.",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    comments = fetch_pending()
    # GitHub Actions output file used to pass values to later workflow steps.
    github_output = os.environ.get("GITHUB_OUTPUT")

    if comments:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(render_report(comments), encoding="utf-8")
        if github_output:
            with open(github_output, "a", encoding="utf-8") as output:
                output.write("has_pending=true\n")
                output.write(f"pending_count={len(comments)}\n")
                output.write(f"report_path={REPORT.relative_to(ROOT).as_posix()}\n")
        print(f"[ok] wrote pending comment report with {len(comments)} item(s): {REPORT.relative_to(ROOT)}")
        return

    if REPORT.exists():
        REPORT.unlink()
        print(f"[ok] removed stale pending comment report: {REPORT.relative_to(ROOT)}")
    else:
        print("[ok] no pending comments and no report to update")

    if github_output:
        with open(github_output, "a", encoding="utf-8") as output:
            output.write("has_pending=false\n")
            output.write("pending_count=0\n")
            output.write(f"report_path={REPORT.relative_to(ROOT).as_posix()}\n")


if __name__ == "__main__":
    main()