#!/usr/bin/env python3
"""
OceanCloud News Fetcher
=======================
Pulls the latest Microsoft SharePoint blog posts and M365 release
communications, rewrites each item in OceanCloud's consulting voice
using an AI API, then:
    1. Generates a standalone article page in articles/news-*.html for users
  2. Injects the latest cards into news.html (replaces each run)
  3. Appends new items to data/archive.json (cumulative, deduplicated)
  4. Regenerates archive.html from the full archive grouped by month
    5. Keeps short generated news detail pages out of sitemap.xml by default

Sources
-------
  Blog   : TechCommunity SharePoint Blog RSS
  Roadmap: Microsoft Release Communications RSS (official M365 release feed)

AI rewrite engines (tried in order, first available wins)
----------------------------------------------------------
    OPENAI_API_KEY    — ChatGPT gpt-4o-mini
    GEMINI_API_KEY    — Google Gemini 2.0 Flash
  None set          — uses truncated original RSS text

Add secrets at: GitHub repo → Settings → Secrets → Actions
"""

import json
import os
import re
import sys
import time
import textwrap
from io import BytesIO
from datetime import datetime, timezone
from html import escape, unescape
from pathlib import Path
from urllib.parse import urljoin

import requests
import feedparser
try:
    from PIL import Image
except ImportError:  # Image dimensions are an enhancement, not a hard dependency.
    Image = None

# ── Configuration ────────────────────────────────────────────────────────────

# Optional Gemini API key for AI rewriting fallback.
GEMINI_KEY      = os.environ.get("GEMINI_API_KEY", "")
# Gemini endpoint URL pre-bound with API key query parameter.
GEMINI_URL      = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    "gemini-2.0-flash:generateContent?key=" + GEMINI_KEY
)

# Optional OpenAI API key (preferred rewrite engine).
OPENAI_KEY      = os.environ.get("OPENAI_API_KEY", "")

# RSS source for official SharePoint blog announcements.
BLOG_RSS_URL    = (
    "https://techcommunity.microsoft.com"
    "/t5/s/gxcuf89792/rss/board?board.id=SPBlog"
)
# RSS source for Microsoft 365 release communications.
ROADMAP_RSS_URL = (
    "https://www.microsoft.com/releasecommunications/api/v2/m365/rss"
)

# Maximum SharePoint blog items fetched per run.
MAX_BLOG        = 6
# Maximum roadmap items fetched per run.
MAX_ROADMAP     = 6

# Topic terms used to filter relevant news content.
RELEVANT_TERMS  = {
    "sharepoint", "copilot", "teams", "viva", "onedrive", "edge",
    "power platform", "power apps", "power automate",
    "purview", "entra", "defender", "syntex", "loop",
    "microsoft 365", "m365"
}

# Repo root used for all generated content paths.
ROOT            = Path(__file__).parent.parent
# News landing page where latest cards are injected.
NEWS_HTML       = ROOT / "news.html"
# Archive landing page rebuilt from full archive data.
ARCHIVE_HTML    = ROOT / "archive.html"

# Cache image dimensions during a run so repeated Microsoft fallback images are fetched once.
IMAGE_DIMENSIONS: dict[str, tuple[int, int] | None] = {}
# Canonical JSON archive store (deduplicated and cumulative).
ARCHIVE_JSON    = ROOT / "data" / "archive.json"
# Directory where generated article pages are written.
ARTICLES_DIR    = ROOT / "articles"
# Sitemap file updated with newly generated article URLs.
SITEMAP_XML     = ROOT / "sitemap.xml"
# Search index used for site-wide search discoverability.
SEARCH_INDEX    = ROOT / "data" / "search-index.json"
# Canonical public base URL for generated links/canonical tags.
SITE_BASE_URL   = "https://oceancloudconsults.com"
# Keep autogenerated short news detail pages out of the index to protect overall site quality.
INDEX_NEWS_ARTICLES = False

# Marker comments delimiting auto-managed news block in news.html.
NEWS_BEGIN      = "<!-- BEGIN:NEWS-CONTENT -->"
NEWS_END        = "<!-- END:NEWS-CONTENT -->"
# Marker comments delimiting auto-managed archive block in archive.html.
ARCHIVE_BEGIN   = "<!-- BEGIN:ARCHIVE-CONTENT -->"
ARCHIVE_END     = "<!-- END:ARCHIVE-CONTENT -->"

# HTTP request headers for RSS and API fetches.
HEADERS         = {"User-Agent": "OceanCloudBot/1.0 (+https://oceancloudconsults.com)"}

# ── Helpers ───────────────────────────────────────────────────────────────────

def strip_html(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def normalize_microsoft_text(text: str) -> str:
    """Fix known source-feed typos before rendering local news pages."""
    if not text:
        return text
    return text.replace("Microsoft 356 Copilot", "Microsoft 365 Copilot")


def local_news_title(title: str, limit: int = 95) -> str:
    """Shorten verbose Microsoft feed titles for local cards and metadata."""
    clean = normalize_microsoft_text(re.sub(r"\s+", " ", title)).strip()
    replacements = [
        ("Microsoft Copilot (Microsoft 365): Microsoft Copilot (Microsoft 365):", "Microsoft 365 Copilot:"),
        ("Microsoft Copilot (Microsoft 365):", "Microsoft 365 Copilot:"),
        ("Microsoft Purview: Data Loss Prevention - Data Loss Prevention to safeguard sensitive information from external web search in Microsoft 365 Copilot and Copilot Chat", "Purview DLP: Safeguard Copilot Web Search"),
        ("Microsoft Purview: Data Loss Prevention -", "Purview DLP:"),
        ("Microsoft Purview: Endpoint Data Loss Prevention -", "Purview Endpoint DLP:"),
        ("Microsoft Purview: Data Lifecycle Management -", "Purview DLM:"),
    ]
    for old, new in replacements:
        clean = clean.replace(old, new)
    clean = re.sub(r"\s+", " ", clean).strip(" -")
    if len(clean) <= limit:
        return clean
    cut = clean.rfind(" ", 0, limit)
    if cut < 60:
        cut = limit
    return clean[:cut].rstrip(" ,;:-") + "..."


def friendly_date(raw: str) -> str:
    if not raw:
        return ""
    from email.utils import parsedate_to_datetime
    try:
        return parsedate_to_datetime(raw).strftime("%B %d, %Y")
    except Exception:
        pass
    try:
        for fmt in ("%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
            try:
                return datetime.strptime(raw[:len(fmt)], fmt).strftime("%B %d, %Y")
            except ValueError:
                continue
    except Exception:
        pass
    return raw[:10]


def iso_date(raw: str) -> str:
    """Return YYYY-MM-DD from an RSS date string."""
    if not raw:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d")
    from email.utils import parsedate_to_datetime
    try:
        return parsedate_to_datetime(raw).strftime("%Y-%m-%d")
    except Exception:
        pass
    try:
        for fmt in ("%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
            try:
                return datetime.strptime(raw[:len(fmt)], fmt).strftime("%Y-%m-%d")
            except ValueError:
                continue
    except Exception:
        pass
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def month_parts(raw: str) -> tuple[str, str]:
    """Return (sort_key '2026-05', label 'May 2026') from an RSS date string."""
    from email.utils import parsedate_to_datetime
    try:
        dt = parsedate_to_datetime(raw)
        return dt.strftime("%Y-%m"), dt.strftime("%B %Y")
    except Exception:
        pass
    try:
        for fmt in ("%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
            try:
                dt = datetime.strptime(raw[:len(fmt)], fmt)
                return dt.strftime("%Y-%m"), dt.strftime("%B %Y")
            except ValueError:
                continue
    except Exception:
        pass
    now = datetime.now(timezone.utc)
    return now.strftime("%Y-%m"), now.strftime("%B %Y")


def slugify(title: str) -> str:
    """Convert a title to a URL-friendly slug (max 60 chars)."""
    s = title.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")[:60].strip("-")


def seo_description(text: str, limit: int = 170) -> str:
    """Return a complete, social-card-safe description without awkward cuts."""
    clean = re.sub(r"\s+", " ", strip_html(text)).strip()
    if len(clean) <= limit:
        return clean
    sentence_end = max(clean.rfind(".", 0, limit), clean.rfind("!", 0, limit), clean.rfind("?", 0, limit))
    if sentence_end >= 90:
        return clean[: sentence_end + 1].strip()
    cut = clean.rfind(" ", 0, limit)
    if cut < 90:
        cut = limit
    clean = clean[:cut].rstrip(" ,;:-")
    if clean and clean[-1] not in ".!?":
        clean += "."
    return clean


def article_slug(item: dict) -> str:
    """Generate a unique filename slug: news-YYYY-MM-<title-slug>."""
    sort_key, _ = month_parts(item["date"])
    return f"news-{sort_key}-{slugify(item['title'])}"


# Keyword → SVG thumbnail mapping (checked in order, first match wins)
TOPIC_IMAGES: list[tuple[str, str]] = [
    ("copilot",        "copilot"),
    ("edge",           "edge"),
    ("viva",           "viva"),
    ("onedrive",       "onedrive"),
    ("power automate", "power-platform"),
    ("power apps",     "power-platform"),
    ("power platform", "power-platform"),
    ("purview",        "purview"),
    ("entra",          "purview"),
    ("defender",       "purview"),
    ("teams",          "teams"),
    ("loop",           "teams"),
    ("syntex",         "sharepoint"),
    ("intranet",       "sharepoint"),
    ("sharepoint",     "sharepoint"),
    ("document",       "sharepoint"),
]

ARTICLE_IMAGE_FALLBACKS = {
    "copilot": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2026/05/preview-copilot-hub.jpg",
        "alt": "Microsoft 365 Copilot Hub preview from Microsoft Adoption",
        "caption": "Representative Microsoft 365 Copilot product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/copilot/",
        "source_label": "Microsoft Adoption",
    },
    "edge-copilot": {
        "url": "https://learn.microsoft.com/en-us/deployEdge/media/microsoft-edge-configure-the-copilot-new-tab-page/img1.png",
        "alt": "Microsoft Edge Copilot new tab page screenshot",
        "caption": "Representative Microsoft Edge Copilot new tab page screenshot.",
        "source_url": "https://learn.microsoft.com/en-us/deployEdge/microsoft-edge-management-configure-the-copilot-new-tab-page",
        "source_label": "Microsoft Learn",
    },
    "edge": {
        "url": "https://learn.microsoft.com/en-us/deployEdge/media/microsoft-edge-configure-the-copilot-new-tab-page/img1.png",
        "alt": "Microsoft Edge browser interface screenshot",
        "caption": "Representative Microsoft Edge browser screenshot from Microsoft Learn.",
        "source_url": "https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-overview",
        "source_label": "Microsoft Learn",
    },
    "outlook": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/09/header-microsoft-teams.jpg",
        "alt": "Microsoft 365 product image from Microsoft Adoption",
        "caption": "Representative Microsoft 365 product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-365/",
        "source_label": "Microsoft Adoption",
    },
    "purview-insider-risk": {
        "url": "https://learn.microsoft.com/en-us/purview/media/insider-risk-triage.png",
        "alt": "Microsoft Purview Insider Risk Management triage screenshot",
        "caption": "Representative Microsoft Purview Insider Risk Management screenshot.",
        "source_url": "https://learn.microsoft.com/en-us/purview/insider-risk-management",
        "source_label": "Microsoft Learn",
    },
    "purview": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2024/11/header-purview.jpg",
        "alt": "Microsoft Purview product image from Microsoft Adoption",
        "caption": "Representative Microsoft Purview product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-purview/",
        "source_label": "Microsoft Adoption",
    },
    "teams-bookable": {
        "url": "https://learn.microsoft.com/en-us/microsoftteams/rooms/media/bookable-desks/automatic-association-image.png",
        "alt": "Microsoft Teams bookable desks automatic association screenshot",
        "caption": "Representative Microsoft Teams bookable desks screenshot.",
        "source_url": "https://learn.microsoft.com/en-us/microsoftteams/rooms/bookable-desks",
        "source_label": "Microsoft Learn",
    },
    "teams-interpreter": {
        "url": "https://learn.microsoft.com/en-us/microsoftteams/media/interpreter-agent-diagram-small.png",
        "alt": "Microsoft Teams Interpreter agent architecture diagram",
        "caption": "Representative Microsoft Teams Interpreter agent diagram.",
        "source_url": "https://learn.microsoft.com/en-us/microsoftteams/interpreter-agent-teams",
        "source_label": "Microsoft Learn",
    },
    "teams": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/09/header-microsoft-teams.jpg",
        "alt": "Microsoft Teams product image from Microsoft Adoption",
        "caption": "Representative Microsoft Teams product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-teams/",
        "source_label": "Microsoft Adoption",
    },
    "sharepoint": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/05/preview-sharepoint.jpg",
        "alt": "Microsoft SharePoint product image from Microsoft Adoption",
        "caption": "Representative Microsoft SharePoint product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/sharepoint/",
        "source_label": "Microsoft Adoption",
    },
    "onedrive": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/10/preview-onedrive.jpg",
        "alt": "Microsoft OneDrive product image from Microsoft Adoption",
        "caption": "Representative Microsoft OneDrive product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/onedrive/",
        "source_label": "Microsoft Adoption",
    },
    "m365": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/09/header-microsoft-teams.jpg",
        "alt": "Microsoft 365 product image from Microsoft Adoption",
        "caption": "Representative Microsoft 365 product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-365/",
        "source_label": "Microsoft Adoption",
    },
}

# TechCommunity blog matching for roadmap items
# Strategy:
#   Pass 1 — keyword match on SPECIFIC (non-roundup) posts (score >= 2).
#            Gives each roadmap item its own unique post image when one exists.
#   Pass 2 — monthly "What's New" roundup post matched by publication month.
#            Unique per product+month; better than a static product photo.
# Falls back to adoption.microsoft.com product images when no match is found.

# product -> TechCommunity board.id  (confirmed to return entries)
PRODUCT_BLOG_FEEDS: dict[str, str] = {
    "teams":      "MicrosoftTeamsBlog",
    "sharepoint": "SPBlog",
    "copilot":    "Microsoft365CopilotBlog",
    "outlook":    "Outlook",
    "onedrive":   "OneDriveBlog",
    "m365":       "Microsoft365Blog",
}

# Per-run RSS cache: product -> list of (lowercased_title, article_url)
_BLOG_CACHE: dict[str, list[tuple[str, str]]] = {}

# Cache for already-fetched OG images: blog_url -> image_url
_OG_IMAGE_CACHE: dict[str, str] = {}

# Patterns that identify monthly "What's New" roundup posts
_ROUNDUP_RE = re.compile(
    r"what.s new|new in microsoft|new in sharepoint|new in teams|new in onedrive|new in outlook|"
    r"new in copilot|monthly|build edition|release notes|new features|roundup|recap",
    re.IGNORECASE,
)

# Month names for date-based matching
_MONTHS = [
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
]


def _get_blog_entries(product: str) -> list[tuple[str, str]]:
    """Fetch and cache all TechCommunity RSS entries for a product (once per run)."""
    if product in _BLOG_CACHE:
        return _BLOG_CACHE[product]
    board_id = PRODUCT_BLOG_FEEDS.get(product, "")
    if not board_id:
        _BLOG_CACHE[product] = []
        return []
    url = (
        "https://techcommunity.microsoft.com"
        f"/t5/s/gxcuf89792/rss/board?board.id={board_id}"
    )
    try:
        feed = feedparser.parse(url, request_headers=HEADERS)
        entries = [(e.title.lower(), e.link) for e in feed.entries]
        _BLOG_CACHE[product] = entries
        print(f"  [blog] Fetched {len(entries)} entries for '{product}'")
    except Exception as exc:
        print(f"  [blog] RSS fetch failed for '{product}': {exc}", file=sys.stderr)
        _BLOG_CACHE[product] = []
    return _BLOG_CACHE[product]


def _fetch_og_cached(url: str) -> str:
    """fetch_og_image() with a per-run cache to avoid duplicate fetches."""
    if url not in _OG_IMAGE_CACHE:
        img = fetch_og_image(url)
        _OG_IMAGE_CACHE[url] = img
    return _OG_IMAGE_CACHE[url]


def _is_valid_image(url: str) -> bool:
    return bool(url) and "open-graph-image" not in url and "RE1Mu3b" not in url


def _keyword_match_entries(
    entries: list[tuple[str, str]], words: list[str], min_score: int = 2
) -> str:
    """Search entries for the best keyword match; return OG image URL or ''."""
    best_url, best_score = "", 0
    for blog_title, blog_url in entries:
        if _ROUNDUP_RE.search(blog_title):
            continue
        score = sum(1 for w in words if w in blog_title)
        if score > best_score:
            best_score, best_url = score, blog_url
    if best_score < min_score or not best_url:
        return ""
    img = _fetch_og_cached(best_url)
    if _is_valid_image(img):
        print(f"  [blog] Keyword match score={best_score} '{best_url[-50:]}' -> {img[:80]}")
        return img
    return ""


def find_blog_image_for_roadmap(item_date: str, title: str, product: str) -> str:
    """Return a TechCommunity OG image for a roadmap item.

    Priority order (most specific → least specific):
    1. Keyword match on the product's own blog (non-roundup posts, score >= 2).
    2. Keyword match on the general Microsoft 365 blog (cross-product catch-all).
    3. Monthly 'What's New' roundup post matched by publish month (per product).

    Each pass produces a unique image for that specific item/month.
    Returns '' if nothing suitable is found.
    """
    stopwords = {
        "microsoft", "teams", "sharepoint", "copilot", "outlook", "onedrive",
        "purview", "with", "from", "that", "this", "your", "when", "will",
        "users", "items", "using", "admin", "center", "support", "feature",
        "update", "adds", "added", "adding", "enables", "allows",
        "experience", "improved", "improvement", "enhancements", "enhancement",
    }
    words = [
        w for w in re.split(r"\W+", title.lower())
        if len(w) > 3 and w not in stopwords
    ]

    # --- Pass 1: keyword match on the product's own blog ---------------------
    entries = _get_blog_entries(product)
    if entries and words:
        img = _keyword_match_entries(entries, words)
        if img:
            return img

    # --- Pass 2: keyword match on general M365 blog (cross-product) ----------
    if product != "m365" and words:
        m365_entries = _get_blog_entries("m365")
        if m365_entries:
            img = _keyword_match_entries(m365_entries, words)
            if img:
                return img

    # --- Pass 3: monthly roundup post matched by publication month -----------
    pub_month_label = ""
    try:
        from email.utils import parsedate_to_datetime
        try:
            dt = parsedate_to_datetime(item_date)
        except Exception:
            dt = datetime.strptime(item_date[:10], "%Y-%m-%d")
        pub_month_label = dt.strftime("%B %Y").lower()   # e.g. "may 2026"
    except Exception:
        pass

    if pub_month_label and entries:
        for blog_title, blog_url in entries:
            if _ROUNDUP_RE.search(blog_title) and pub_month_label in blog_title:
                img = _fetch_og_cached(blog_url)
                if _is_valid_image(img):
                    print(f"  [blog] Monthly roundup '{blog_title[:60]}' -> {img[:80]}")
                    return img

    return ""


ARTICLE_SECONDARY_IMAGE_FALLBACKS = {
    "copilot": {
        "url": "https://learn.microsoft.com/en-us/viva/insights/org-team-insights/images/copilot-dashboard-readiness-full.png",
        "alt": "Microsoft Copilot Dashboard readiness report screenshot",
        "caption": "Microsoft Viva Insights screenshot showing Copilot readiness reporting.",
        "source_url": "https://learn.microsoft.com/en-us/viva/insights/org-team-insights/copilot-dashboard",
        "source_label": "Microsoft Learn",
    },
    "edge-copilot": {
        "url": "https://learn.microsoft.com/en-us/deployedge/media/microsoft-edge-configure-the-copilot-new-tab-page/img2.png",
        "alt": "Microsoft Edge Copilot new tab page work cards screenshot",
        "caption": "Microsoft Edge screenshot showing Copilot new tab page work cards.",
        "source_url": "https://learn.microsoft.com/en-us/deployEdge/microsoft-edge-management-configure-the-copilot-new-tab-page",
        "source_label": "Microsoft Learn",
    },
    "edge": {
        "url": "https://learn.microsoft.com/en-us/deployEdge/media/microsoft-edge-configure-the-copilot-new-tab-page/img1.png",
        "alt": "Microsoft Edge browser screenshot from Microsoft Learn",
        "caption": "Representative Microsoft Edge browser screenshot from Microsoft Learn.",
        "source_url": "https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-overview",
        "source_label": "Microsoft Learn",
    },
    "outlook": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/09/header-microsoft-teams.jpg",
        "alt": "Microsoft 365 product image from Microsoft Adoption",
        "caption": "Representative Microsoft 365 product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-365/",
        "source_label": "Microsoft Adoption",
    },
    "purview-insider-risk": {
        "url": "https://learn.microsoft.com/en-us/purview/media/insider-risk-activity-explorer.png",
        "alt": "Microsoft Purview Insider Risk Management activity explorer screenshot",
        "caption": "Microsoft Purview screenshot showing Insider Risk Management activity explorer.",
        "source_url": "https://learn.microsoft.com/en-us/purview/insider-risk-management-activities",
        "source_label": "Microsoft Learn",
    },
    "purview": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2024/11/header-purview.jpg",
        "alt": "Microsoft Purview product image from Microsoft Adoption",
        "caption": "Representative Microsoft Purview product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-purview/",
        "source_label": "Microsoft Adoption",
    },
    "teams-bookable": {
        "url": "https://learn.microsoft.com/en-us/microsoftteams/devices/media/book-future-meetings-from-panel-device/panel-bookinfuture-01.jpg",
        "alt": "Microsoft Teams panel home screen with room availability",
        "caption": "Microsoft Teams panel screenshot showing room availability and booking context.",
        "source_url": "https://learn.microsoft.com/en-us/microsoftteams/devices/book-future-meetings-from-panel-device",
        "source_label": "Microsoft Learn",
    },
    "teams-interpreter": {
        "url": "https://learn.microsoft.com/en-us/microsoftteams/media/interpreter-agent-diagram-small.png",
        "alt": "Microsoft Teams Interpreter agent architecture diagram",
        "caption": "Representative Microsoft Teams Interpreter agent diagram.",
        "source_url": "https://learn.microsoft.com/en-us/microsoftteams/interpreter-agent-teams",
        "source_label": "Microsoft Learn",
    },
    "teams": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/09/header-microsoft-teams.jpg",
        "alt": "Microsoft Teams product image from Microsoft Adoption",
        "caption": "Representative Microsoft Teams product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-teams/",
        "source_label": "Microsoft Adoption",
    },
    "sharepoint": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/05/preview-sharepoint.jpg",
        "alt": "Microsoft SharePoint product image from Microsoft Adoption",
        "caption": "Representative Microsoft SharePoint product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/sharepoint/",
        "source_label": "Microsoft Adoption",
    },
    "m365": {
        "url": "https://adoption.microsoft.com/wp-content/uploads/2025/09/header-microsoft-teams.jpg",
        "alt": "Microsoft 365 product image from Microsoft Adoption",
        "caption": "Representative Microsoft 365 product image from Microsoft Adoption.",
        "source_url": "https://adoption.microsoft.com/en-us/microsoft-365/",
        "source_label": "Microsoft Adoption",
    },
}


def image_for_item(item: dict) -> str:
    article_image = item.get("_article_image") or {}
    if article_image.get("url"):
        return article_image["url"].replace("../assets/", "assets/", 1)
    haystack = (item["title"] + " " + item.get("summary", "")).lower()
    for keyword, img_name in TOPIC_IMAGES:
        if keyword in haystack:
            return f"assets/news/{img_name}.svg"
    return "assets/news/m365-roadmap.svg" if item["css_tag"] == "tag-roadmap" else "assets/news/m365.svg"


def image_dimension_attrs(url: str, image: dict | None = None) -> str:
    """Return width/height attributes for a remote raster image when available."""
    if image and image.get("width") and image.get("height"):
        return f' width="{int(image["width"])}" height="{int(image["height"])}"'

    if Image is None or not url.startswith("http"):
        return ""

    clean_url = unescape(url)
    if clean_url not in IMAGE_DIMENSIONS:
        try:
            resp = requests.get(clean_url, headers=HEADERS, timeout=15, allow_redirects=True)
            resp.raise_for_status()
            with Image.open(BytesIO(resp.content)) as img:
                IMAGE_DIMENSIONS[clean_url] = img.size
        except Exception as exc:
            IMAGE_DIMENSIONS[clean_url] = None
            print(f"  [warn] Could not read image dimensions: {exc}", file=sys.stderr)

    size = IMAGE_DIMENSIONS.get(clean_url)
    if not size:
        return ""
    width, height = size
    return f' width="{width}" height="{height}"'


def fetch_og_image(url: str) -> str:
    """Return a public Open Graph/Twitter image for a source article, if present."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=15, allow_redirects=True)
        resp.raise_for_status()
    except Exception as exc:
        print(f"  [warn] Could not fetch source image: {exc}", file=sys.stderr)
        return ""

    html = resp.text
    patterns = [
        r'<meta[^>]+(?:property|name)=["\'](?:og:image|twitter:image)["\'][^>]+content=["\']([^"\']+)["\']',
        r'<meta[^>]+content=["\']([^"\']+)["\'][^>]+(?:property|name)=["\'](?:og:image|twitter:image)["\']',
    ]
    for pattern in patterns:
        match = re.search(pattern, html, flags=re.IGNORECASE)
        if not match:
            continue
        image_url = urljoin(resp.url, unescape(match.group(1)))
        if image_url and "RE1Mu3b" not in image_url:
            return image_url
    return ""


_PRODUCT_PREFIXES: list[tuple[str, str]] = [
    ("microsoft teams:",           "teams"),
    ("teams:",                     "teams"),
    ("microsoft sharepoint:",      "sharepoint"),
    ("sharepoint:",                "sharepoint"),
    ("microsoft purview:",         "purview"),
    ("purview:",                   "purview"),
    ("microsoft 365 copilot:",     "copilot"),
    ("m365 copilot:",              "copilot"),
    ("microsoft copilot:",         "copilot"),
    ("copilot:",                   "copilot"),
    ("microsoft onedrive:",        "onedrive"),
    ("onedrive:",                  "onedrive"),
    ("microsoft outlook:",         "outlook"),
    ("outlook:",                   "outlook"),
    ("microsoft edge:",            "edge"),
    ("edge:",                      "edge"),
    ("microsoft viva:",            "viva"),
    ("viva:",                      "viva"),
]


def _detect_product(haystack: str, title: str = "") -> str:
    """Return the product bucket for a news item.

    Checks the title colon-prefix first (most reliable — e.g. 'Microsoft Teams:
    ...' → 'teams' even when the body mentions Copilot), then falls back to
    keyword search in the full lowercased haystack.
    """
    t = title.lower() if title else ""
    for prefix, product in _PRODUCT_PREFIXES:
        if t.startswith(prefix):
            return product
    # Keyword fallback — more-specific products checked before generic ones
    if "purview" in haystack or "data loss prevention" in haystack or re.search(r"\bdlp\b", haystack):
        return "purview"
    if "sharepoint" in haystack:    return "sharepoint"
    if "onedrive" in haystack:      return "onedrive"
    if "copilot" in haystack:       return "copilot"
    if "teams" in haystack:         return "teams"
    if "outlook" in haystack:       return "outlook"
    if "edge" in haystack:          return "edge"
    if "viva" in haystack:          return "viva"
    return "m365"


def article_image_for_item(item: dict) -> dict:
    """Choose a real source image for a generated news article.

    Priority order:
    1. Blog items   -> real OG image scraped from the TechCommunity article URL
    2. Any item     -> specific hardcoded screenshot (exact sub-topic match)
    3. Roadmap items -> OG image from best-matching TechCommunity product blog post
    4. Any item     -> adoption.microsoft.com real product photo fallback
    """
    title   = item.get("title", "")
    summary = item.get("summary", "")

    # 1. Blog posts: scrape OG image directly from the TechCommunity article
    if item.get("css_tag") == "tag-blog":
        source_image = fetch_og_image(item.get("url", ""))
        if source_image:
            return {
                "url":          source_image,
                "alt":          f"Microsoft TechCommunity image for {title}",
                "caption":      "Original Microsoft TechCommunity image for this announcement.",
                "source_url":   item["url"],
                "source_label": item.get("source", "Microsoft TechCommunity"),
            }

    haystack = (title + " " + summary).lower()

    # 2. Specific hardcoded screenshots for exact sub-topics
    if "edge" in haystack:
        if "copilot new tab" in haystack or "new tab page" in haystack:
            return ARTICLE_IMAGE_FALLBACKS["edge-copilot"]
        return ARTICLE_IMAGE_FALLBACKS["edge"]
    if "insider risk" in haystack:
        return ARTICLE_IMAGE_FALLBACKS["purview-insider-risk"]
    if "bookable desk" in haystack or re.search(r"\bdesk\b", haystack):
        return ARTICLE_IMAGE_FALLBACKS["teams-bookable"]
    if "interpreter" in haystack:
        return ARTICLE_IMAGE_FALLBACKS["teams-interpreter"]

    # 3. For roadmap items: search TechCommunity product blog for a matching post
    if item.get("css_tag") == "tag-roadmap":
        product = _detect_product(haystack, title)
        blog_img = find_blog_image_for_roadmap(item.get("date", ""), title, product)
        if blog_img:
            product_label = {
                "teams": "Microsoft Teams", "sharepoint": "Microsoft SharePoint",
                "copilot": "Microsoft 365 Copilot", "outlook": "Microsoft Outlook",
                "onedrive": "Microsoft OneDrive",
            }.get(product, "Microsoft 365")
            return {
                "url":          blog_img,
                "alt":          f"Microsoft TechCommunity image for {title}",
                "caption":      f"Image from the Microsoft TechCommunity {product_label} blog.",
                "source_url":   "https://techcommunity.microsoft.com/",
                "source_label": "Microsoft TechCommunity",
            }

    # 4. adoption.microsoft.com real product photo (much better than SVGs)
    product = _detect_product(haystack, title)
    return ARTICLE_IMAGE_FALLBACKS.get(product, ARTICLE_IMAGE_FALLBACKS["m365"])


def image_bucket_for_item(item: dict) -> str:
    """Return the topic bucket used to pick representative secondary imagery."""
    haystack = (item.get("title", "") + " " + item.get("summary", "")).lower()
    if "edge" in haystack:
        if "copilot new tab" in haystack or "new tab page" in haystack:
            return "edge-copilot"
        return "edge"
    if "outlook" in haystack:
        return "outlook"
    if "insider risk" in haystack:
        return "purview-insider-risk"
    if "purview" in haystack or "data loss prevention" in haystack or re.search(r"\bdlp\b", haystack):
        return "purview"
    if "bookable desk" in haystack or re.search(r"\bdesk\b", haystack):
        return "teams-bookable"
    if "interpreter" in haystack:
        return "teams-interpreter"
    if "teams" in haystack:
        return "teams"
    if "sharepoint" in haystack:
        return "sharepoint"
    if "copilot" in haystack:
        return "copilot"
    return "m365"


def secondary_article_image_for_item(item: dict) -> dict:
    """Choose a second real image for generated news article context."""
    bucket = image_bucket_for_item(item)
    return ARTICLE_SECONDARY_IMAGE_FALLBACKS.get(bucket, ARTICLE_SECONDARY_IMAGE_FALLBACKS["m365"])


# Matches any <figure class="article-image">...</figure> block (with or without SVG)
_FIGURE_RE = re.compile(
    r'\s*<figure class="article-image">\s*'
    r'<img[^>]*/>\s*'
    r'<figcaption[^>]*>.*?</figcaption>\s*'
    r'</figure>',
    re.DOTALL,
)


def refresh_article_images(html: str, item: dict) -> str:
    """Replace article figure blocks with the current best images for this item.

    First SVG figure → replaced with primary image.
    First non-SVG figure whose URL matches the current best → left unchanged.
    Additional figures → removed (keeps one clean image per article).
    Called every run even for existing articles so images stay current.
    """
    art_img = item.get("_article_image") or {}
    new_url = art_img.get("url", "")
    if not new_url:
        return html

    # If the first figure already has the correct image, nothing to do
    first_match = _FIGURE_RE.search(html)
    if first_match and new_url in first_match.group(0):
        return html

    new_figure = (
        '\n      <figure class="article-image">\n'
        '        <img src="' + escape(new_url) + '" '
        'alt="' + escape(art_img.get("alt", "")) + '" '
        'loading="lazy" decoding="async" referrerpolicy="no-referrer" />\n'
        '        <figcaption>' + escape(art_img.get("caption", "")) +
        ' <a href="' + escape(art_img.get("source_url", "")) + '" '
        'target="_blank" rel="noopener noreferrer">Source: ' +
        escape(art_img.get("source_label", "")) + '</a>.</figcaption>\n'
        '      </figure>'
    )

    state = [False]

    def _replacer(m, _s=state, _rep=new_figure):
        if not _s[0]:
            _s[0] = True
            return _rep
        return ""

    return _FIGURE_RE.sub(_replacer, html)


def topic_for_item(item: dict) -> str:
    title = item["title"].lower()
    haystack = (item["title"] + " " + item.get("summary", "")).lower()

    title_prefix_topics = [
        ("microsoft teams:", "teams"),
        ("teams:", "teams"),
        ("microsoft purview:", "purview"),
        ("purview:", "purview"),
        ("microsoft edge:", "edge"),
        ("edge:", "edge"),
        ("microsoft onedrive:", "onedrive"),
        ("onedrive:", "onedrive"),
        ("microsoft viva:", "viva"),
        ("viva:", "viva"),
        ("microsoft copilot:", "copilot"),
        ("copilot:", "copilot"),
    ]
    for prefix, topic in title_prefix_topics:
        if title.startswith(prefix):
            return topic

    if "sharepoint" in title:
        return "sharepoint"
    if "power automate" in title or "power apps" in title or "power platform" in title:
        return "power-platform"
    if "document management" in title or item.get("css_tag") == "tag-blog":
        return "sharepoint"

    fallback_terms = [
        ("edge", "edge"),
        ("teams", "teams"),
        ("purview", "purview"),
        ("data loss prevention", "purview"),
        ("dlp", "purview"),
        ("onedrive", "onedrive"),
        ("sharepoint", "sharepoint"),
        ("copilot", "copilot"),
        ("power automate", "power-platform"),
        ("power apps", "power-platform"),
        ("power platform", "power-platform"),
        ("viva", "viva"),
    ]
    for keyword, topic in fallback_terms:
        if re.search(r"\b" + re.escape(keyword) + r"\b", haystack):
            return topic

    for keyword, img_name in TOPIC_IMAGES:
        if keyword in haystack:
            return img_name
    return "other"


def is_relevant(entry) -> bool:
    haystack = (
        entry.get("title", "") + " " + strip_html(entry.get("summary", ""))
    ).lower()
    return any(term in haystack for term in RELEVANT_TERMS)


# ── AI prompts ────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = textwrap.dedent("""\
    You are a senior content writer for OceanCloud, a certified Microsoft 365
    consulting firm in Dallas, TX. OceanCloud specialises in SharePoint, Teams,
    Power Platform, Copilot, and M365 security.

    Rewrite the Microsoft announcement below as a 2-3 sentence expert commentary
    for OceanCloud's news page. Rules:
    - Explain the business impact clearly.
    - Mention how organisations can take advantage (link to OceanCloud's
      expertise where natural, e.g. "migration", "governance", "Copilot rollout").
    - Confident, authoritative, slightly forward-looking tone.
    - Do NOT start with "OceanCloud". Do NOT use bullet points.
    - Output ONLY the 2-3 sentence commentary, nothing else.
""")

ARTICLE_PROMPT = textwrap.dedent("""\
    You are a senior content writer for OceanCloud, a certified Microsoft 365
    consulting firm. Write a 380-450 word expert article about this Microsoft
    announcement for OceanCloud's website.

    Structure your response EXACTLY as follows (use these exact headings):

    ## What's Changing
    [2-3 sentences clearly explaining the feature or update]

    ## Business Impact
    [2-3 sentences on why this matters for IT teams and decision-makers]

    ## What You Should Do
    - [Specific action item]
    - [Specific action item]
    - [Specific action item]
    - [Specific action item]

    Rules:
    - Professional, confident, forward-looking tone
    - Practical advice for Microsoft 365 admins and business leaders
    - Do NOT repeat the title as a heading or first sentence
    - Output ONLY the structured content — nothing before ## What's Changing
""")


# ── AI rewrite (short commentary for news cards) ──────────────────────────────

def _truncate(summary: str) -> str:
    return (summary[:280] + "…") if len(summary) > 280 else summary


def _openai(title: str, summary: str, prompt: str, max_tokens: int) -> str | None:
    if not OPENAI_KEY:
        return None
    try:
        import openai
        client = openai.OpenAI(api_key=OPENAI_KEY)
        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            max_tokens=max_tokens,
            temperature=0.65,
            messages=[
                {"role": "system", "content": prompt},
                {"role": "user", "content": f"Title: {title}\n\nOriginal text: {summary[:800]}"},
            ],
        )
        return resp.choices[0].message.content.strip()
    except Exception as exc:
        print(f"  [warn] ChatGPT error: {exc}", file=sys.stderr)
        return None


def _gemini(title: str, summary: str, prompt: str, max_tokens: int) -> str | None:
    if not GEMINI_KEY:
        return None
    body = f"Title: {title}\n\nOriginal text: {summary[:800]}"
    payload = {
        "contents": [{"parts": [{"text": prompt + "\n\n" + body}]}],
        "generationConfig": {"temperature": 0.65, "maxOutputTokens": max_tokens},
    }
    try:
        resp = requests.post(GEMINI_URL, json=payload, timeout=20)
        resp.raise_for_status()
        return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
    except Exception as exc:
        print(f"  [warn] Gemini error: {exc}", file=sys.stderr)
        return None


def ai_rewrite(title: str, summary: str) -> str:
    """Short 2-3 sentence commentary for news cards. ChatGPT → Gemini → text."""
    result = _openai(title, summary, SYSTEM_PROMPT, 220)
    if result:
        print("  [info] Used ChatGPT for card rewrite")
        return result
    result = _gemini(title, summary, SYSTEM_PROMPT, 220)
    if result:
        print("  [info] Used Gemini for card rewrite")
        return result
    print("  [warn] No AI key available — using original text", file=sys.stderr)
    return _truncate(summary)


def ai_article_body(title: str, summary: str) -> str:
    """Longer structured article body. ChatGPT → Gemini → fallback."""
    result = _openai(title, summary, ARTICLE_PROMPT, 700)
    if result:
        print("  [info] Used ChatGPT for article body")
        return result
    result = _gemini(title, summary, ARTICLE_PROMPT, 700)
    if result:
        print("  [info] Used Gemini for article body")
        return result
    return summary[:800]


# ── Markdown → HTML (for article body) ───────────────────────────────────────

def md_to_html(text: str) -> str:
    """Convert simple markdown (##, ###, -, *) to HTML."""
    lines = text.split("\n")
    parts = []
    in_ul = False
    for line in lines:
        line = line.rstrip()
        if line.startswith("## "):
            if in_ul:
                parts.append("</ul>")
                in_ul = False
            parts.append(f"<h2>{escape(line[3:])}</h2>")
        elif line.startswith("### "):
            if in_ul:
                parts.append("</ul>")
                in_ul = False
            parts.append(f"<h3>{escape(line[4:])}</h3>")
        elif line.startswith("- ") or line.startswith("* "):
            if not in_ul:
                parts.append("<ul>")
                in_ul = True
            parts.append(f"<li>{escape(line[2:])}</li>")
        elif line:
            if in_ul:
                parts.append("</ul>")
                in_ul = False
            parts.append(f"<p>{escape(line)}</p>")
    if in_ul:
        parts.append("</ul>")
    return "\n      ".join(parts)


# ── Article page generator ────────────────────────────────────────────────────

def generate_article_page(item: dict, commentary: str, body_md: str, slug: str) -> str:
    """Build a complete HTML article page for a news item."""
    date_str   = friendly_date(item["date"])
    pub_date   = iso_date(item["date"])
    source_title = item["title"]
    title      = local_news_title(source_title)
    ms_url     = item["url"]
    is_roadmap = item["css_tag"] == "tag-roadmap"
    tag_label  = source_tag_label(item)
    tag_color  = "rgba(0,180,216,.12)" if is_roadmap else "rgba(59,130,246,.12)"
    tag_tc     = "#00b4d8" if is_roadmap else "#60a5fa"
    canonical  = f"{SITE_BASE_URL}/articles/{slug}"
    short      = title[:45] + ("…" if len(title) > 45 else "")
    body_html  = md_to_html(body_md)
    desc_text  = seo_description(commentary)
    desc       = escape(desc_text)
    article_image = item.get("_article_image") or article_image_for_item(item)
    image_url = article_image.get("url", "")
    image_html = ""
    if image_url:
        image_attrs = image_dimension_attrs(image_url, article_image)
        image_html = f"""
      <figure class="article-image">
        <img src="{escape(image_url)}" alt="{escape(article_image.get('alt', title))}"{image_attrs} loading="lazy" decoding="async" referrerpolicy="no-referrer" />
        <figcaption>{escape(article_image.get('caption', 'Microsoft product image.'))} <a href="{escape(article_image.get('source_url', ms_url))}" target="_blank" rel="noopener noreferrer">Source: {escape(article_image.get('source_label', item['source']))}</a>.</figcaption>
      </figure>
"""
    secondary_image = item.get("_secondary_article_image") or secondary_article_image_for_item(item)
    secondary_image_html = ""
    if secondary_image.get("url") and secondary_image.get("url") != image_url:
        secondary_image_attrs = image_dimension_attrs(secondary_image["url"], secondary_image)
        secondary_image_html = f"""
      <figure class="article-image">
        <img src="{escape(secondary_image['url'])}" alt="{escape(secondary_image.get('alt', title))}"{secondary_image_attrs} loading="lazy" decoding="async" referrerpolicy="no-referrer" />
        <figcaption>{escape(secondary_image.get('caption', 'Related Microsoft product image.'))} <a href="{escape(secondary_image.get('source_url', ms_url))}" target="_blank" rel="noopener noreferrer">Source: {escape(secondary_image.get('source_label', item['source']))}</a>.</figcaption>
      </figure>
"""
    og_image = article_image.get("og_url") or image_url or f"{SITE_BASE_URL}/assets/og-news.jpg"
    if og_image == f"{SITE_BASE_URL}/assets/og-home.jpg":
        og_image = f"{SITE_BASE_URL}/assets/og-news.jpg"
    og_image_alt = article_image.get("alt") or title
    json_title = json.dumps(title, ensure_ascii=False)
    json_desc = json.dumps(desc_text, ensure_ascii=False)
    json_image = json.dumps(og_image, ensure_ascii=False)
    json_short = json.dumps(short, ensure_ascii=False)
    product_name = tag_label.replace(" Roadmap", "").replace(" Blog", "").replace(" Showcase", "")
    kw_parts = [f"Microsoft {product_name}", product_name, "Microsoft 365", "M365 updates"]
    if is_roadmap:
        kw_parts.extend([f"{product_name} roadmap", "M365 roadmap"])
    else:
        kw_parts.extend([f"{product_name} news", "Microsoft 365 blog"])
    kw_parts.append("OceanCloud")
    keywords_str = escape(", ".join(kw_parts))

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="theme-color" content="#0077b6" />
  <title>{escape(title)} | OceanCloud</title>
  <meta name="description" content="{desc}" />
  <meta name="keywords" content="{keywords_str}" />
    <meta name="robots" content="{'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1' if INDEX_NEWS_ARTICLES else 'noindex, follow, noarchive'}" />
  <meta name="author" content="OceanCloud Consultants" />
  <meta name="geo.region" content="US" />
  <meta name="geo.placename" content="Dallas, TX" />
  <meta name="geo.position" content="32.7767;-96.7970" />
  <link rel="canonical" href="{canonical}" />
  <meta property="og:type"        content="article" />
  <meta property="og:site_name"   content="OceanCloud Consultants" />
  <meta property="og:title"       content="{escape(title)}" />
  <meta property="og:description" content="{desc}" />
  <meta property="og:url"         content="{canonical}" />
  <meta property="og:image"       content="{escape(og_image)}" />
  <meta property="og:image:alt"   content="{escape(og_image_alt)}" />
  <meta property="og:locale"      content="en_US" />
    <meta name="twitter:card"        content="summary_large_image" />
    <meta name="twitter:site"        content="@oceancloud_x" />
  <meta name="twitter:title"       content="{escape(title)}" />
  <meta name="twitter:description" content="{desc}" />
  <meta name="twitter:image"       content="{escape(og_image)}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="../css/style.css?v=3" />
  <link rel="stylesheet" href="../css/pages.css?v=11" />
  <link rel="stylesheet" href="../css/darkstar.css?v=3" />
  <link rel="stylesheet" href="../css/article.css?v=6" />
    <link rel="icon" type="image/svg+xml" href="../favicon.svg" />
    <link rel="apple-touch-icon" href="{SITE_BASE_URL}/assets/apple-touch-icon.png" />
    <link rel="alternate" hreflang="en-US" href="{canonical}" />
    <link rel="alternate" type="application/rss+xml" title="OceanCloud M365 News" href="{SITE_BASE_URL}/feed.xml" />
    <link rel="alternate" type="text/markdown" title="OceanCloud LLM Discovery" href="{SITE_BASE_URL}/llms.txt" />
  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@graph": [
      {{
        "@type": "Article",
        "@id": "{canonical}#article",
        "headline": {json_title},
        "url": "{canonical}",
        "mainEntityOfPage": "{canonical}",
        "datePublished": "{pub_date}",
        "dateModified": "{pub_date}",
        "author": {{ "@id": "{SITE_BASE_URL}/#organization" }},
        "publisher": {{ "@id": "{SITE_BASE_URL}/#organization" }},
                "description": {json_desc},
                "image": {json_image},
                "inLanguage": "en-US",
                "isPartOf": {{ "@id": "{SITE_BASE_URL}/#website" }}
            }},
            {{
                "@type": "Organization",
                "@id": "{SITE_BASE_URL}/#organization",
                "name": "OceanCloud Consultants",
                "alternateName": "OceanCloud",
                "legalName": "OceanCloud Consultants",
                "url": "{SITE_BASE_URL}/",
                "telephone": "+1-469-809-4053",
                "email": "oceancloudconsults@gmail.com",
                "address": {{
                    "@type": "PostalAddress",
                    "addressLocality": "Dallas",
                    "addressRegion": "TX",
                    "addressCountry": "US"
                }},
                "areaServed": {{ "@type": "Country", "name": "United States" }},
                "contactPoint": [
                    {{
                        "@type": "ContactPoint",
                        "name": "Main phone",
                        "telephone": "+1-469-809-4053",
                        "contactType": "sales and customer service",
                        "description": "Available Monday-Friday, 9:00 AM-6:00 PM Eastern Time."
                    }},
                    {{
                        "@type": "ContactPoint",
                        "name": "WhatsApp",
                        "telephone": "+1-917-675-3126",
                        "contactType": "customer support",
                        "contactOption": "WhatsApp",
                        "description": "Available Monday-Friday, 9:00 AM-6:00 PM Eastern Time."
                    }}
                ]
            }},
            {{
                "@type": "WebSite",
                "@id": "{SITE_BASE_URL}/#website",
                "url": "{SITE_BASE_URL}/",
                "name": "OceanCloud",
                "publisher": {{ "@id": "{SITE_BASE_URL}/#organization" }},
                "inLanguage": "en-US"
      }},
      {{
        "@type": "BreadcrumbList",
        "itemListElement": [
          {{ "@type": "ListItem", "position": 1, "name": "Home",  "item": "{SITE_BASE_URL}" }},
          {{ "@type": "ListItem", "position": 2, "name": "News",  "item": "{SITE_BASE_URL}/news" }},
          {{ "@type": "ListItem", "position": 3, "name": {json_short}, "item": "{canonical}" }}
        ]
      }}
    ]
  }}
  </script>
  <style>
  .article-section{{padding:60px 0 100px;}}
  .article-wrap{{max-width:800px;margin:0 auto;}}
  .article-meta{{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin-bottom:28px;padding-bottom:24px;border-bottom:1px solid rgba(255,255,255,.07);}}
  .art-tag{{font-size:.72rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;padding:4px 12px;border-radius:50px;background:{tag_color};color:{tag_tc};}}
  .art-date,.art-read{{font-size:.8rem;color:var(--text-dim);}}
  .article-intro{{font-size:1.05rem;color:#b8cfe0;line-height:1.85;margin-bottom:24px;}}
  .article-wrap h2{{font-size:clamp(1.25rem,3vw,1.6rem);font-weight:800;margin:48px 0 14px;color:var(--white);letter-spacing:-.03em;}}
  .article-wrap h3{{font-size:1.05rem;font-weight:700;margin:30px 0 10px;color:#c8daea;}}
  .article-wrap p{{color:var(--text-mid);line-height:1.85;margin:0 0 18px;}}
  .article-wrap ul,.article-wrap ol{{color:var(--text-mid);line-height:1.85;padding-left:22px;margin:0 0 18px;}}
  .article-wrap li{{margin-bottom:7px;}}
  .article-wrap strong{{color:var(--white);}}
  .article-wrap a{{color:#00b4d8;}}
  .ms-source-ref{{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:18px 22px;margin-top:40px;font-size:.88rem;color:var(--text-dim);}}
  .ms-source-ref a{{color:#00b4d8;text-decoration:none;}}
  .ms-source-ref a:hover{{text-decoration:underline;}}
  .related-section{{margin-top:64px;padding-top:48px;border-top:1px solid rgba(255,255,255,.08);}}
  .related-label{{font-size:.72rem;font-weight:700;color:var(--text-dim);text-transform:uppercase;letter-spacing:.1em;margin-bottom:16px;}}
  .related-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;}}
  .related-card{{padding:18px 20px;border-radius:12px;text-decoration:none;display:flex;flex-direction:column;gap:6px;border:1px solid rgba(255,255,255,.07);transition:border-color .2s;}}
  .related-card:hover{{border-color:rgba(0,180,216,.3);}}
  .rc-topic{{font-size:.68rem;font-weight:700;color:#00b4d8;text-transform:uppercase;letter-spacing:.08em;}}
  .rc-title{{font-size:.88rem;font-weight:600;color:var(--white);line-height:1.4;}}
  .rc-read{{font-size:.78rem;color:var(--text-dim);margin-top:2px;}}
  .related-card:hover .rc-title{{color:#00b4d8;}}
  </style>
</head>
<body>

<a href="#main-content" class="skip-link">Skip to content</a>
<div id="c-dot"></div>
<div id="c-ring"></div>

<nav id="navbar">
  <div class="container nav-inner">
    <a href="/" class="nav-logo"><div class="logo-mark">OC</div><span class="logo-text">Ocean<span>Cloud</span></span></a>
    <ul class="nav-links" id="navLinks">
      <li><a href="/"><span class="nav-num">01</span>Home</a></li>
      <li><a href="../services"><span class="nav-num">02</span>Services</a></li>
      <li><a href="../about"><span class="nav-num">03</span>About</a></li>
      <li><a href="../case-studies"><span class="nav-num">04</span>Work</a></li>
      <li><a href="../news" class="active-link"><span class="nav-num">05</span>News</a></li>
      <li><a href="../guides"><span class="nav-num">06</span>Guides</a></li>
      <li><a href="../contact" class="nav-cta">Get In Touch</a></li>
    </ul>
    <a href="../search" class="nav-search-btn" aria-label="Search"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg></a>
    <button class="hamburger" id="hamburger" aria-label="Toggle navigation" aria-expanded="false"><span></span><span></span><span></span></button>
  </div>
</nav>

<section id="main-content" class="page-hero article-hero particle-hero">
  <canvas data-particles='{{"count":30,"color":"0,180,216","maxDist":90,"speed":0.15,"opacity":0.18}}'></canvas>
  <div class="orb orb-cyan" style="width:340px;height:340px;top:-80px;right:-60px;"></div>
  <div class="orb orb-purple" style="width:220px;height:220px;bottom:-40px;left:10%;"></div>
  <div class="container particle-hero-inner">
    <div class="page-hero-content">
      <nav class="breadcrumb"><a href="/">Home</a><span>/</span><a href="../news">News</a><span>/</span><span>{escape(short)}</span></nav>
      <h1>{escape(title)}</h1>
    </div>
  </div>
</section>

<section class="article-section">
  <div class="container">
    <div class="article-wrap">

      <div class="article-meta">
        <span class="art-tag">{escape(tag_label)}</span>
        {f'<span class="art-date">{escape(date_str)}</span>' if date_str else ""}
        <span class="art-read">3 min read</span>
      </div>

      <p class="article-intro">{escape(commentary)}</p>
{image_html}

      {body_html}
{secondary_image_html}

      <div class="ms-source-ref">
        <strong>Original announcement:</strong>
        <a href="{escape(ms_url)}" target="_blank" rel="noopener noreferrer">{escape(title)}</a>
        &mdash; {escape(item['source'])}
      </div>

      <div class="related-section">
        <p class="related-label">Related Guides</p>
        <div class="related-grid"></div>
      </div>

    </div>
  </div>
</section>

<footer class="site-footer">
  <div class="container footer-grid">
    <div class="footer-brand">
      <div class="nav-logo"><div class="logo-mark">OC</div><span class="logo-text">Ocean<span>Cloud</span></span></div>
      <p class="footer-tagline">Microsoft 365 &amp; SharePoint consultants helping businesses work smarter.</p>
    </div>
    <div class="footer-col">
      <h4>Company</h4>
      <ul>
        <li><a href="../about">About Us</a></li>
        <li><a href="../case-studies">Case Studies</a></li>
        <li><a href="../news">News</a></li>
        <li><a href="../archive">News Archive</a></li>
        <li><a href="../guides">Guides &amp; Tips</a></li>
        <li><a href="../faq">FAQ</a></li>
      </ul>
    </div>
    <div class="footer-col">
      <h4>Services</h4>
      <ul>
        <li><a href="../services">SharePoint Development</a></li>
        <li><a href="../services">Teams Configuration</a></li>
        <li><a href="../services">M365 Migration</a></li>
        <li><a href="../services">Power Platform</a></li>
      </ul>
    </div>
    <div class="footer-col">
      <h4>Legal</h4>
      <ul>
        <li><a href="../privacy">Privacy Policy</a></li>
        <li><a href="../terms">Terms of Service</a></li>
        <li><a href="../cookies">Cookie Policy</a></li>
        <li><a href="../contact">Contact Us</a></li>
      </ul>
    </div>
  </div>
  <div class="footer-bottom"><div class="container"><p>&copy; 2026 OceanCloud Consultants. All rights reserved.</p></div></div>
</footer>

<button id="back-to-top" aria-label="Back to top"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="18 15 12 9 6 15"/></svg></button>

<script src="../js/main.js?v=9"></script>
<script src="../js/consent.js?v=5"></script>
<script src="../js/chat.js?v=7"></script>
<script src="../js/particles.js?v=6"></script>
<script src="../js/weather.js?v=6"></script>
<script src="../js/share.js?v=1"></script>
<script src="../js/article.js?v=5"></script>
<script src="../js/comments.js?v=7"></script>
</body>
</html>"""


# ── Sitemap updater ───────────────────────────────────────────────────────────

def update_sitemap(new_slugs: list[str]) -> None:
    """Append new article URLs to sitemap.xml if not already present."""
    if not INDEX_NEWS_ARTICLES:
        print("[ok] sitemap.xml unchanged; generated news detail pages are noindex.")
        return
    if not SITEMAP_XML.exists() or not new_slugs:
        return
    content = SITEMAP_XML.read_text(encoding="utf-8")
    today   = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    entries = ""
    added   = 0
    for slug in new_slugs:
        url = f"{SITE_BASE_URL}/articles/{slug}"
        if url in content:
            continue
        entries += (
            f"\n  <url>\n"
            f"    <loc>{url}</loc>\n"
            f"    <lastmod>{today}</lastmod>\n"
            f"    <changefreq>monthly</changefreq>\n"
            f"    <priority>0.6</priority>\n"
            f"  </url>\n"
        )
        added += 1
    if not entries:
        return
    content = content.replace("</urlset>", entries + "</urlset>")
    SITEMAP_XML.write_text(content, encoding="utf-8")
    print(f"[ok] sitemap.xml updated with {added} new article URL(s).")


# ── Search index updater ──────────────────────────────────────────────────────

def update_search_index(new_items: list[dict]) -> None:
    """Append new news article entries to data/search-index.json."""
    if not SEARCH_INDEX.exists() or not new_items:
        return
    try:
        index = json.loads(SEARCH_INDEX.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"  [warn] Could not read search-index.json: {exc}", file=sys.stderr)
        return

    existing_ids = {entry.get("id", "") for entry in index}
    added = 0
    for item in new_items:
        slug   = item.get("_slug", "")
        if not slug:
            continue
        entry_id = f"articles-{slug}"
        if entry_id in existing_ids:
            continue
        date_display = friendly_date(item["date"])
        commentary   = item.get("_commentary", item.get("summary", ""))[:300]
        body_text    = f"{item['title']} | OceanCloud {date_display} 3 min read {commentary}"
        index.append({
            "id":          entry_id,
            "type":        "article",
            "tag":         "Article",
            "title":       item["title"],
            "heading":     item["title"],
            "excerpt":     commentary,
            "body":        body_text,
            "url":         f"articles/{slug}",
            "dateDisplay": date_display,
            "dateSort":    "",
        })
        existing_ids.add(entry_id)
        added += 1

    if added:
        SEARCH_INDEX.write_text(
            json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"[ok] search-index.json updated with {added} new article entry/entries.")


# ── Fetchers ──────────────────────────────────────────────────────────────────

def fetch_blog() -> list[dict]:
    print("Fetching SharePoint blog RSS…")
    print(f"  URL: {BLOG_RSS_URL}")
    try:
        feed = feedparser.parse(BLOG_RSS_URL, request_headers=HEADERS)
        status = getattr(feed, "status", "unknown")
        bozo   = getattr(feed, "bozo", False)
        print(f"  HTTP status: {status}  |  bozo: {bozo}  |  entries: {len(feed.entries)}")
        if bozo and not feed.entries:
            print(f"  [warn] bozo_exception: {getattr(feed, 'bozo_exception', '')}", file=sys.stderr)
        posts = []
        for entry in feed.entries[:MAX_BLOG]:
            title = normalize_microsoft_text(entry.get("title", "Untitled"))
            summary = normalize_microsoft_text(strip_html(entry.get("summary", "")))[:800]
            posts.append({
                "title":   title,
                "url":     entry.get("link", "#"),
                "date":    entry.get("published", ""),
                "summary": summary,
                "source":  "SharePoint Blog",
                "css_tag": "tag-blog",
            })
        print(f"  -> {len(posts)} blog posts selected")
        return posts
    except Exception as exc:
        print(f"  [error] Blog fetch failed: {exc}", file=sys.stderr)
        return []


def fetch_roadmap() -> list[dict]:
    print("Fetching M365 Release Communications RSS…")
    print(f"  URL: {ROADMAP_RSS_URL}")
    try:
        feed = feedparser.parse(ROADMAP_RSS_URL, request_headers=HEADERS)
        status = getattr(feed, "status", "unknown")
        bozo   = getattr(feed, "bozo", False)
        print(f"  HTTP status: {status}  |  bozo: {bozo}  |  entries: {len(feed.entries)}")
        if bozo and not feed.entries:
            print(f"  [warn] bozo_exception: {getattr(feed, 'bozo_exception', '')}", file=sys.stderr)
        items, matched = [], 0
        for entry in feed.entries:
            if is_relevant(entry):
                matched += 1
            else:
                continue
            title = normalize_microsoft_text(entry.get("title", "Untitled"))
            summary = normalize_microsoft_text(strip_html(entry.get("summary", "")))[:800]
            items.append({
                "title":   title,
                "url":     entry.get("link", "https://www.microsoft.com/en-us/microsoft-365/roadmap"),
                "date":    entry.get("published", ""),
                "summary": summary,
                "source":  "M365 Roadmap",
                "css_tag": "tag-roadmap",
            })
            if len(items) >= MAX_ROADMAP:
                break
        print(f"  -> {len(items)} roadmap items (relevance matched {matched}/{len(feed.entries)})")
        return items
    except Exception as exc:
        print(f"  [error] Roadmap fetch failed: {exc}", file=sys.stderr)
        return []


# ── News HTML ─────────────────────────────────────────────────────────────────

_PRODUCT_TAG_LABELS: dict[str, str] = {
    "teams":          "Teams Roadmap",
    "sharepoint":     "SharePoint Roadmap",
    "copilot":        "Copilot Roadmap",
    "purview":        "Purview Roadmap",
    "onedrive":       "OneDrive Roadmap",
    "outlook":        "Outlook Roadmap",
    "edge":           "Edge Roadmap",
    "viva":           "Viva Roadmap",
    "power-platform": "Power Platform Roadmap",
    "m365":           "M365 Roadmap",
}


def source_tag_label(item: dict, topic: str = "") -> str:
    """Return the human-readable category label for a news card or article tag."""
    if item.get("css_tag") == "tag-roadmap":
        if not topic:
            haystack = (item.get("title", "") + " " + item.get("summary", "")).lower()
            topic = _detect_product(haystack, item.get("title", ""))
        return _PRODUCT_TAG_LABELS.get(topic, "M365 Roadmap")
    return item.get("source", "SharePoint Blog")


def card_html(item: dict, commentary: str) -> str:
    date_str    = friendly_date(item["date"])
    img         = image_for_item(item)
    img_attrs   = image_dimension_attrs(img)
    img_alt     = (item.get("_article_image") or {}).get("alt", item["source"])
    source_slug = "roadmap" if item["css_tag"] == "tag-roadmap" else "blog"
    topic_slug  = topic_for_item(item)
    topic_fallbacks = {
        "sharepoint", "teams", "edge", "onedrive", "copilot",
        "power-platform", "purview", "viva",
    }
    fallback_img = (
        f"/assets/news/{topic_slug}.svg"
        if topic_slug in topic_fallbacks
        else "/assets/news/m365-roadmap.svg" if item["css_tag"] == "tag-roadmap" else "/assets/news/m365.svg"
    )
    local_url   = item.get("_article_url", item["url"])
    ms_url      = item["url"]
    title       = local_news_title(item["title"])
    return f"""\
      <article class="news-card glass" data-source="{source_slug}" data-topic="{topic_slug}">
        <div class="nc-image-wrap">
          <img class="nc-image" src="{escape(img)}" alt="{escape(img_alt)}"{img_attrs} loading="lazy" onerror="this.onerror=null;this.src='{escape(fallback_img)}';" />
        </div>
        <div class="nc-meta">
          <span class="nc-tag {item['css_tag']}">{escape(source_tag_label(item, topic_slug))}</span>
          {f'<span class="nc-date">{escape(date_str)}</span>' if date_str else ''}
        </div>
        <h3 class="nc-title">
          <a href="{escape(local_url)}" rel="nofollow">
            {escape(title)}
          </a>
        </h3>
        <p class="nc-body">{escape(commentary)}</p>
        <div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;">
          <a class="nc-link" href="{escape(local_url)}" rel="nofollow">Read article &#8599;</a>
          <a class="nc-link" href="{escape(ms_url)}" target="_blank" rel="noopener noreferrer" style="opacity:.6;font-size:.75rem;">Microsoft &#8599;</a>
        </div>
      </article>"""


def build_news_block(items: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    cards = "\n".join(card_html(it, it["_commentary"]) for it in items)
    return (
        f"{NEWS_BEGIN}\n"
        f'    <div class="news-grid" id="news-grid">\n'
        f"{cards}\n"
        f"    </div>\n"
        f'    <p class="news-updated">Last updated: {now} &nbsp;&middot;&nbsp; '
        f'Sources: <a href="https://techcommunity.microsoft.com/category/content_management/blog/spblog" '
        f'target="_blank" rel="noopener">Microsoft TechCommunity SharePoint Blog</a> &amp; '
        f'<a href="https://www.microsoft.com/en-us/microsoft-365/roadmap" '
        f'target="_blank" rel="noopener">M365 Roadmap</a> &nbsp;&middot;&nbsp; '
        f'<a href="archive">View full archive &#8594;</a></p>\n'
        f"{NEWS_END}"
    )


# ── Archive ───────────────────────────────────────────────────────────────────

def load_archive() -> list[dict]:
    if not ARCHIVE_JSON.exists():
        return []
    try:
        return json.loads(ARCHIVE_JSON.read_text(encoding="utf-8")).get("items", [])
    except Exception:
        return []


def save_archive(items: list[dict]) -> None:
    ARCHIVE_JSON.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "items":        items,
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    }
    ARCHIVE_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def merge_archive(archive: list[dict], new_items: list[dict]) -> tuple[list[dict], int]:
    """Add new items to archive, deduped by URL. Stores article_slug for local page links."""
    seen = {it["url"] for it in archive}
    added = 0
    for it in new_items:
        if it["url"] in seen:
            continue
        sort_key, label = month_parts(it["date"])
        archive.append({
            "title":         it["title"],
            "url":           it["url"],
            "date_friendly": friendly_date(it["date"]) or label,
            "month_sort":    sort_key,
            "month_label":   label,
            "source":        it["source"],
            "css_tag":       it["css_tag"],
            "article_slug":  it.get("_slug", ""),
        })
        seen.add(it["url"])
        added += 1
    archive.sort(key=lambda x: (x.get("month_sort", ""), x.get("date_friendly", "")), reverse=True)
    return archive, added


def build_archive_block(archive: list[dict]) -> str:
    if not archive:
        return (
            f"{ARCHIVE_BEGIN}\n"
            "    <p class=\"archive-empty\">No archived articles yet — check back after the next weekly update.</p>\n"
            f"{ARCHIVE_END}"
        )

    groups: dict[str, dict] = {}
    order:  list[str]       = []
    for it in archive:
        key = it["month_sort"]
        if key not in groups:
            groups[key] = {"label": it["month_label"], "items": []}
            order.append(key)
        groups[key]["items"].append(it)

    parts = []
    for key in order:
        g     = groups[key]
        count = len(g["items"])
        rows  = ""
        for it in g["items"]:
            short      = source_tag_label(it)
            art_slug   = it.get("article_slug", "")
            link_url   = f"/articles/{art_slug}" if art_slug else it["url"]
            link_attrs = ' rel="nofollow"' if art_slug else ' target="_blank" rel="noopener noreferrer"'
            title      = local_news_title(it["title"])
            rows += (
                f'        <li class="am-item">\n'
                f'          <span class="nc-tag {escape(it["css_tag"])}">{short}</span>\n'
                f'          <a href="{escape(link_url)}"{link_attrs}>'
                f'{escape(title)}</a>\n'
                f'          <span class="am-date">{escape(it["date_friendly"])}</span>\n'
                f'        </li>\n'
            )
        parts.append(
            f'    <div class="archive-month reveal">\n'
            f'      <h3 class="am-heading">\n'
            f'        <span class="grad-text">{escape(g["label"])}</span>\n'
            f'        <span class="am-count">{count} item{"s" if count != 1 else ""}</span>\n'
            f'      </h3>\n'
            f'      <ul class="am-list">\n'
            f'{rows}'
            f'      </ul>\n'
            f'    </div>\n'
        )

    now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    return (
        f"{ARCHIVE_BEGIN}\n"
        + "".join(parts)
        + f'    <p class="news-updated">Archive updated: {now} &nbsp;&middot;&nbsp; {len(archive)} total items</p>\n'
        + f"{ARCHIVE_END}"
    )


def inject(html: str, begin: str, end: str, block: str) -> tuple[str, int]:
    pattern = re.escape(begin) + r".*?" + re.escape(end)
    return re.subn(pattern, block, html, flags=re.DOTALL)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    if not NEWS_HTML.exists():
        print(f"[error] {NEWS_HTML} not found.", file=sys.stderr)
        sys.exit(1)

    ARTICLES_DIR.mkdir(exist_ok=True)

    blog_items    = fetch_blog()
    roadmap_items = fetch_roadmap()
    all_items     = blog_items + roadmap_items

    if not all_items:
        print("[warn] No content fetched — news.html not updated.", file=sys.stderr)
        sys.exit(1)

    # ── Rewrite short commentary + generate article pages ─────────────────────
    print(f"\nProcessing {len(all_items)} items…")
    new_article_slugs: list[str] = []

    for item in all_items:
        print(f"  • {item['title'][:70]}")

        # Short commentary for news card
        item["_commentary"] = ai_rewrite(item["title"], item["summary"])
        item["_article_image"] = article_image_for_item(item)
        item["_secondary_article_image"] = secondary_article_image_for_item(item)
        time.sleep(0.3)

        # Standalone article page (only if file doesn't already exist)
        slug      = article_slug(item)
        art_path  = ARTICLES_DIR / f"{slug}.html"
        item["_slug"]        = slug
        item["_article_url"] = f"/articles/{slug}"

        if not art_path.exists():
            print(f"    -> generating article page: {slug}.html")
            body_md = ai_article_body(item["title"], item["summary"])
            time.sleep(0.3)
            art_html = generate_article_page(item, item["_commentary"], body_md, slug)
            art_path.write_text(art_html, encoding="utf-8")
            new_article_slugs.append(slug)
        else:
            # Article body already written — only refresh images so they stay
            # current without touching the AI-generated prose or metadata.
            current_html = art_path.read_text(encoding="utf-8")
            refreshed_html = refresh_article_images(current_html, item)
            if refreshed_html != current_html:
                art_path.write_text(refreshed_html, encoding="utf-8")
                print(f"    -> refreshed images in: {slug}.html")
            else:
                print(f"    -> article page up to date, no image change")

    # ── Update sitemap ────────────────────────────────────────────────────────
    update_sitemap(new_article_slugs)

    # ── Update search index ───────────────────────────────────────────────────
    if INDEX_NEWS_ARTICLES:
        new_indexed = [it for it in all_items if it.get("_slug") in new_article_slugs]
        update_search_index(new_indexed)
    else:
        print("[ok] search-index.json unchanged; generated news detail pages are noindex.")

    # ── Update news.html ──────────────────────────────────────────────────────
    html = NEWS_HTML.read_text(encoding="utf-8")
    updated, n = inject(html, NEWS_BEGIN, NEWS_END, build_news_block(all_items))
    if n == 0:
        print(f"[error] News markers not found in news.html", file=sys.stderr)
        sys.exit(1)
    NEWS_HTML.write_text(updated, encoding="utf-8")
    print(f"\n[ok] news.html updated with {len(all_items)} items.")

    # ── Update archive ────────────────────────────────────────────────────────
    print("\nUpdating archive…")
    archive = load_archive()
    archive, added = merge_archive(archive, all_items)
    save_archive(archive)
    print(f"  -> {added} new items added ({len(archive)} total in archive)")

    if ARCHIVE_HTML.exists():
        arc_html = ARCHIVE_HTML.read_text(encoding="utf-8")
        updated_arc, m = inject(arc_html, ARCHIVE_BEGIN, ARCHIVE_END, build_archive_block(archive))
        if m == 0:
            print("[warn] Archive markers not found in archive.html", file=sys.stderr)
        else:
            ARCHIVE_HTML.write_text(updated_arc, encoding="utf-8")
            print(f"[ok] archive.html updated with {len(archive)} total items.")
    else:
        print("[warn] archive.html not found — skipping.", file=sys.stderr)

    if new_article_slugs:
        print(f"\n[ok] {len(new_article_slugs)} new article page(s) created in articles/")


if __name__ == "__main__":
    main()
